# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/ip/FONT/FONT.xci
# IP: The module: 'FONT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/ip/FONT/FONT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FONT'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/ip/FONT/FONT.xci
# IP: The module: 'FONT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/ip/FONT/FONT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FONT'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
