# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/ip/FONT1/FONT1.xci
# IP: The module: 'FONT1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/ip/FONT1/FONT1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FONT1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/ip/FONT1/FONT1.xci
# IP: The module: 'FONT1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/ip/FONT1/FONT1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FONT1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
