# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/SWORD.xdc

# IP: ip/Text_RAM/Text_RAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Text_RAM || ORIG_REF_NAME==Text_RAM} -quiet] -quiet
