# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7k325tffg676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {E:/Verilog Project/Architecture/MCPU/MCPU.cache/wt} [current_project]
set_property parent.project_path {E:/Verilog Project/Architecture/MCPU/MCPU.xpr} [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {e:/Verilog Project/Architecture/MCPU/MCPU.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{E:/Verilog Project/Organization/OExp4/coe/MCPU.coe}}
add_files c:/Users/T460P/Downloads/CharROM.coe
add_files {{E:/Verilog Project/Architecture/Material/NewShell.coe}}
add_files {{E:/Verilog Project/Architecture/Material/background2.coe}}
add_files {{e:/Verilog Project/Architecture/ArchExp1/ArchExp1.srcs/sources_1/ip/FONT1.coe}}
read_verilog -library xil_defaultlib {
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/new/ALU.v}
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/imports/Desktop/ByteMask.v}
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/imports/OExp4/Counter_3_IO.v}
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/new/Debug.v}
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/new/Display.v}
  C:/Users/T460P/Downloads/GPIO.v
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/imports/OExp4/Hex2Seg.v}
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/imports/OExp4/HexTo8Seg.v}
  C:/Users/T460P/Downloads/LEDP2S_IO.v
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/imports/OExp4/MC14495_ZJU.vf}
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/imports/Desktop/MCPU2.v}
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/new/MIO_BUS.v}
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/imports/OExp4/MUX2T1_64.v}
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/imports/OExp4/MUX2T1_8.v}
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/imports/OExp4/MUX4T1_32.v}
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/imports/OExp4/MUX4T1_5.v}
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/imports/OExp4/MUX8T1_32.vf}
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/imports/OExp4/MUX8T1_8.vf}
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/imports/OExp4/Multi_8CH32.v}
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/imports/OExp4/P2S_IO.v}
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/imports/OExp4/PIO_IO.v}
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/imports/Desktop/PS2.v}
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/imports/OExp4/REG32.v}
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/imports/OExp4/Regs.v}
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/imports/SDK/Reprog.v}
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/imports/OExp4/SAnti_jitter_IO.v}
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/imports/OExp4/SEnter_2_32_IO.v}
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/imports/OExp4/SSeg_map.v}
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/imports/OExp4/Seg_map.v}
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/imports/Desktop/StoreMask.v}
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/new/Unsigned_Divider.v}
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/new/VRAM_Text.v}
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/imports/OExp4/clk_div.v}
  {E:/Verilog Project/Hardware System/Test/Test.srcs/sources_1/imports/IOTest-src/vga.v}
  {E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/new/SWORD.v}
}
read_ip -quiet {{E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/ip/Text_RAM/Text_RAM.xci}}
set_property used_in_implementation false [get_files -all {{e:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/ip/Text_RAM/Text_RAM_ooc.xdc}}]

read_ip -quiet {{E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/ip/FONT/FONT.xci}}
set_property used_in_implementation false [get_files -all {{e:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/ip/FONT/FONT_ooc.xdc}}]

read_ip -quiet {{E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/ip/VRAM/VRAM.xci}}
set_property used_in_implementation false [get_files -all {{e:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/ip/VRAM/VRAM_ooc.xdc}}]

read_ip -quiet {{E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/ip/RAM_B/RAM_B.xci}}
set_property used_in_implementation false [get_files -all {{e:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/ip/RAM_B/RAM_B_ooc.xdc}}]

read_ip -quiet {{E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/ip/Signed_Multiplier/Signed_Multiplier.xci}}

read_ip -quiet {{E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/ip/Unsigned_Multiplier/Unsigned_Multiplier.xci}}

read_ip -quiet {{e:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/ip/FONT1/FONT1.xci}}
set_property used_in_implementation false [get_files -all {{e:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/ip/FONT1/FONT1_ooc.xdc}}]

read_edif {{E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/imports/OExp4/Counter_x.ngc}}
read_edif {{E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/imports/OExp4/PIO.ngc}}
read_edif C:/Users/T460P/Downloads/LEDP2S.ngc
read_edif {{E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/imports/OExp4/P2S.ngc}}
read_edif {{E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/imports/OExp4/SEnter_2_32.ngc}}
read_edif {{E:/Verilog Project/Architecture/MCPU/MCPU.srcs/sources_1/imports/OExp4/SAnti_jitter.ngc}}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{E:/Verilog Project/Architecture/MCPU/MCPU.srcs/constrs_1/new/SWORD.xdc}}
set_property used_in_implementation false [get_files {{E:/Verilog Project/Architecture/MCPU/MCPU.srcs/constrs_1/new/SWORD.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top SWORD -part xc7k325tffg676-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef SWORD.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file SWORD_utilization_synth.rpt -pb SWORD_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
